export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_FEATURED_PRODUCT = 'GET_FEATURED_PRODUCT';
export const GET_LATEST_PRODUCT = 'GET_LATEST_PRODUCT';
export const GET_EXCLUSIVE_PRODUCT = 'GET_EXCLUSIVE_PRODUCT';
export const GET_PRODUCT_DESCRIPTION = 'GET_PRODUCT_DESCRIPTION';
export const GET_RELATED_PRODUCTS = 'GET_RELATED_PRODUCTS';
export const PRODUCTS_SPINNER = 'PRODUCTS_SPINNER';
export const QUOTES = 'QUOTES';